

// Template Scanner Configuration
// Boilerplate code for all Scanner Configurations


// initialize variables
// holds the previous scan result
var previousScan = [""];
// used to hold comparison of previous and current scan result
var notInLastRead = false;


/** 
 * This method is invoked on a successful code read.
 * @param decodeResults - Array of results and scan information produced by the scanner.
 * @param readerProperties - Array of Scanner Properties.
 * @param output - Array allowing customization of the output behavior of the Scanner.
 **/ 
function onResult(decodeResults, readerProperties, output) {
	// if the result was successfully decoded
	if (decodeResults[0].decoded) {
        // process the initial results ('|' -> ',' and remove all spaces)
		var processedResults = processResultString(decodeResults[0].content);
        // check the code output against the previously scanned code(s)
        notInLastRead = isStringNotInArray(previousScan, decodeResults[0].content);
        if (notInLastRead) {
            // shift out the previous scan and add the new scan into the list
            previousScan.shift();
            previousScan.push(decodeResults[0].content);
            /**
             * Add additional scan result validation conditions here.
             */
            // generate a final output string, send it to the output module, and show a message on the screen
            var final = generateOutputString(readerProperties, processedResults);
            output.content = final;
            output.OLED = "<Message>";
        // the code scanned matches the previously scanned code
        } else {
            duplicateScanError();
        }
    // results do not pass the validations
    } else {
        previousScan = dataValidationError(decodeResults, output, previousScan);
    }
}


// Helpers


/**
 * Checks the passed Array for the passed String.
 * @param {string[]} array - The array to search in.
 * @param {String} string - The string to search `array` for.
 * @returns {boolean}
 */
function isStringNotInArray(array, string) {
	for (var i = 0; i < array.length; i++) {
		if (array[i] === string) {
			return false;
		}
	}
	return true;
}

/**
 * Processes a result string to remove spaces and replace bars with commas.
 * @param raw - The raw result string from the scanner output.
 * @returns {string[]}
 **/
function processResultString(raw) {
	// ensure the input is a string
	var input_string = String(raw);
    // split the string into an array by the bar symbol
    var input_list = input_string.split("|");
    // remove whitespace, ampersand, and newline characters from each field
    for (var i = 0; i < length(input_list); i++) {
        _string = input_list[i];
        _string = _string.replace(/\s/g, "");
        _string = _string.replace(/\\000026/g, "");
        _string = _string.replace(/\n/g, "");
        input_list[i] = _string;
    }
	// return the processed result array
	return input_list;
}

/**
 * Creates a final, formatted string that can be sent to the output module.
 * @param {Array} readerProperties - The `readerProperties` item created by the Scanner.
 * @param {string[]} processedResultList - The list of processed fields created by `processResultString()`
 * @returns {null}
 */
function generateOutputString(readerProperties, processedResultList) {
    // add the scanner information to the output
    // scanner_name
    var outputString = String(readerProperties.name);
    // scan time/date
    outputString += "," + String(readerProperties.trigger.creationDate).replace(/\s/g, "-");
    // scan results
    for (var i = 0; i < length(processedResultList); i++) {
        outputString += "," + String(processedResultList[i]);
    }
    // remove unnecessary GMT from the timestamp
    outputString = outputString.replace("-GMT-0400-", "");
}

/**
 * Throws a duplicate scan error to the Scanner. 
 * Sends a data validation failure command, sends a warning to the screen, and voids output.
 * @param {Array} output - The output module generated by the Scanner.
 * @returns {null}
 */
function duplicateScanError(output) {
    dmccCommand("OUTPUT.DATAVALID-FAIL");
    output.OLED = "Duplicate Label scanned";
    output.content = "";
}

/**
 * Throws a data validation error to the Scanner.
 * Sends a data validation failure command, sends a warning to the screen, and voids output.
 * Additionally, shifts `previousScan` to the `decodeResults` content. 
 * Returns the new `previousScan` array.
 * @param {*} decodeResults - The `decodeResults` produced by the Scanner.
 * @param {*} output - The `output` module created by the Scanner.
 * @param {*} previousScan - The `previousScan` array initialized in the beginning of the script.
 * @returns {string[]}
 */
function dataValidationError(decodeResults, output, previousScan) {
    dmccCommand("OUTPUT.DATAVALID-FAIL");
    output.OLED = "Please scan a Master Label to receive a shipment";
    output.content = "";
    // update the last scan
    previousScan.shift();
    previousScan.push(decodeResults[0].content);
    return previousScan
}

/**
 * Validates a string as a PO Number using a regular expression test.
 * @param {string} string 
 * @returns {boolean}
 */
function validatePONumber(string) {
	// set a regex pattern for PO Number format (0-9A-Za-z-_) and check it
	var poPattern = /^[\w\d\-\_]+$/;
	if (poPattern.test(string)) {
		return true;	
	} else {
		return false;	
	}	
}

/**
 * Validates a string as a Part Number using a regular expression test.
 * @param {string} string 
 * @returns {boolean}
 */
function validatePartNumber(string) {
	// set regex patterns for Part Number formats
	var pnPattern1 = /^\w\w-\w\w\w-\w\w\w\w\w-\w\w\w\w$/;
	var pnPattern2 = /^\w\w-\w\w\w-\w\w\w\w\w-\w\w\w\w-\w\w\w$/;
	var pnPattern3 = /^\w\w-\w\w\w-\w\w\w\w\w-\w\w\w\w-\w\w$/;
	var pnPattern4 = /^\w\w-\w\w\w\w-\w\w\w\w\w-\w\w\w\w-\w\w\w$/;
	// check for each of the defined part number formats
	if (pnPattern1.test(string)) {
		return true;	
	}
	if (pnPattern2.test(string)) {
		return true;	
	}
	if (pnPattern3.test(string)) {
		return true;	
	}
	if (pnPattern4.test(string)) {
		return true;	
	}
	// none of the checks were successful
	return false;
}

function validateDateNoTime(string) {}

function validateShift(string) {}

function validatePartName(string) {}

function validateJBKNumber(string) {}

function validateLotNumber(string) {}

function validateModel(string) {}

function validateQuantity(string) {}

function validateDieNumber(string) {}